### ISSUE TITLE
Can't load shaders

### ISSUE THREAD

**Issue by AndresDiaz1** [alvarosabu/modern-three#3]
Hi, nice repo!
I cloned it, installed dependencies but running the app, it throws this error: `[vite] Internal server error: shaderChunks.at is not a function` I know it is related to `vite-plugin-glsl`.

(just in order to try to find the issue, I replaced the `ShaderMaterial` for a `MeshStandardMaterial` and just console log the `vertexShader` import, also throws the error above.)

Have you faced the same error?

**Comment by AndresDiaz1** [comment]
In deed is related to the `vite-plugin-glsl`library, on `loadShaders.js library file.

I had to replace: 
`const caller = shaderChunks.at(-1);`
to
`const caller = shaderChunks[shaderChunks.length-1]`

Closing this issue due is not related to your library.

**Comment by alvarosabu** [comment]
@AndresDiaz1 Thanks anyhow for raising the issue, it will help anyone that has it
